# Generated by Django 3.0.6 on 2020-05-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecture_id',
            field=models.UUIDField(default='d7455a61', editable=False, primary_key=True, serialize=False),
        ),
    ]
