# Generated by Django 3.0.6 on 2020-05-25 17:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('lecture_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('week', models.IntegerField(validators=[django.core.validators.MaxValueValidator(52), django.core.validators.MinValueValidator(1)])),
                ('url', models.CharField(max_length=250, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Course')),
            ],
        ),
    ]
