# Generated by Django 3.0.6 on 2020-05-25 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_lecture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='lecture_id',
            new_name='lecture_id_we',
        ),
    ]
