# Generated by Django 3.0.6 on 2020-05-25 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_auto_20200525_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='lecture_id_we',
            new_name='lecture_id',
        ),
    ]
